In [71]:
import pandas as pd
import mysql.connector
import pdfkit

In [82]:
connection = mysql.connector.connect(host='localhost',
                                    user='root',
                                    password='cloud@mojo321',
                                    database='cloudmojo_tech_attendance_db')
my_cursor = connection.cursor()
# my_cursor.execute("select distinct EmployeeID from employees order by EmployeeID;")
my_cursor.execute("select distinct EmployeeID,EmployeeName from employees where EmployeeName not like 'del%' order by EmployeeID;")
result = []
for i in my_cursor.fetchall():
    result.append((i[0],i[1]))

for i in result:
    print(i[0],i[1])
my_cursor.execute(f"select * from attendancelogs where EmployeeID = 93 and InTime between '2024-03-01 00:00:00' AND '2024-03-31 00:00:00';")
for i in my_cursor.fetchall():
    print(i)
print(len(result))
for i in result:
    df= pd.DataFrame()
    # my_cursor.execute(f"select * from attendancelogs where EmployeeID = {i[0]} and InTime between '2024-03-01 00:00:00' AND '2024-03-31 00:00:00';")
    my_cursor.execute(f"select atl.EmployeeID,e.EmployeeName,e.EmployeeCode,atl.InTime,atl.OutTime,atl.Duration,atl.EarlyBy from employees e join attendancelogs atl on atl.EmployeeId = e.EmployeeId where atl.EmployeeID = {i[0]} and InTime between '2024-03-01 00:00:00' AND '2024-03-31 00:00:00';")
    data=[]
    for j in my_cursor.fetchall():
        data.append(j)
    df=pd.DataFrame(data)
    html_string = df.to_html()
    config = pdfkit.configuration(wkhtmltopdf=r"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe")
    pdfkit.from_string(html_string,f"{i[1]}.pdf",configuration=config)
    # df.to_csv(f"cmt_files/{i[1]}.csv")
connection.close()

73 Sohail Memon
74 Alfiya Shaikh
75 Kajal Gupta
76 Moazzam Shaikh
77 Adnan Shaikh
79 Vaishnavi Kadam
80 Supraja Jakkula
81 Mridula Parasar
82 Aditya Bera
83 Sagar Amdoskar
84 Virja Samant
86 Prajesh Waghela
87 Fiona Coutinho
88 Peter Crasta
89 Shaiju Varughese
90 Saquib Khan
91 Helna Korgaonkar
92 Soni Shivamol
93 Namrata More
94 Kavita Chavan
95 Shruti Karkera
96 Priyanka Satve
97 Sharmila Jadhav
98 Jyotsna Chinchwalkar
99 Trupti  Nate
100 Sonali Gondhe
101 Rohit Gaikwad
102 Sachin Salunke
103 Ramkrishna Ahirrao
104 Sohail Chougle
105 Irfan Merchant
106 Ujas Pandya
107 Shrikant Patil
108 Milind Patil
109 Jitendra Mestry
110 Divesh Indap
111 Ashutosh Kadam
112 Shraddha Sonawane
114 Milind Tele
115 Naveen Kumar S
117 Kazim Shaikh
118 Imran Shaikh
119 052
120 Punyashree Bhatt
121 Asmita Kadam
122 041
123 Aleslam Ansari
124 Ashish Panchal
125 Vaibhavi Patel
127 Syed Shahnawaz Zaidi
128 Ziauddin Syed
129 Anupam Saikia
130 03
131 Sherin John
132 Ketan Bhagat
133 A Parvez Banatwala
134 064
135 04
136 Nikhil Patil
137 Dax Thomas
138 8
139 17
140 23
141 065
142 66
145 69
149 73
152 76
154 78
156 80
157 81
161 Abhirup Chandra
162 Anil Saindane
163 Nilesh Hanjankar
164 Nitisha Manglik
165 Swapnil Kale
166 Roselyn Kinny
167 Sumit Tare
168 Prachi Pandey
169 Mayuri Shirsekar
170 Ayushi Chavan
171 Susant Dasari
172 Shirish Keni
173 Ravikumar Banelera
174 Saurav Shetty
175 Rahul Chauhan
(59438, '01-Mar-24', 93, '2024-03-01 10:12:49', 'TD', '2024-03-01 18:25:59', 'TD', 493, 42, 0, 'FALSE', '', 0, 0, 0, '', '10:12:in(TD),10:12:(TD),18:25:out(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 47)
(59439, '02-Mar-24', 93, '2024-03-02 10:01:23', 'TD', '2024-03-02 18:28:53', 'TD', 507, 31, 0, 'FALSE', '', 0, 0, 0, '', '10:01:in(TD),10:01:(TD),18:10:out(TD),18:28:in(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 33)
(59441, '04-Mar-24', 93, '2024-03-04 10:13:06', 'TD', '2024-03-04 18:28:55', 'TD', 495, 43, 0, 'FALSE', '', 0, 0, 0, '', '10:13:in(TD),10:13:(TD),18:08:out(TD),18:28:in(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 45)
(59442, '05-Mar-24', 93, '2024-03-05 10:14:47', 'TD', '2024-03-05 18:26:39', 'TD', 492, 44, 0, 'FALSE', '', 0, 0, 0, '', '10:14:in(TD),18:26:out(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 48)
(59443, '06-Mar-24', 93, '2024-03-06 10:10:47', 'TD', '2024-03-06 18:29:45', 'TD', 499, 40, 0, 'FALSE', '', 0, 0, 0, '', '10:10:in(TD),18:29:out(TD),18:29:(TD),18:29:(TD),18:29:(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 41)
(59444, '07-Mar-24', 93, '2024-03-07 10:14:39', 'TD', '2024-03-07 18:27:07', 'TD', 493, 44, 0, 'FALSE', '', 0, 0, 0, '', '10:14:in(TD),10:14:(TD),18:27:out(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 47)
(59445, '08-Mar-24', 93, '2024-03-08 10:01:44', 'TD', '2024-03-08 18:38:26', 'TD', 517, 31, 0, 'FALSE', '', 0, 0, 0, '', '10:01:in(TD),18:38:out(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 23)
(59446, '09-Mar-24', 93, '2024-03-09 10:10:07', 'TD', '2024-03-09 18:20:00', 'TD', 490, 40, 0, 'FALSE', '', 0, 0, 0, '', '10:10:in(TD),10:14:(TD),10:14:(TD),18:20:out(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 50)
(59448, '11-Mar-24', 93, '2024-03-11 10:10:47', 'TD', '2024-03-11 16:56:00', 'TD', 406, 40, 94, 'FALSE', '', 0, 0, 0, '', '10:10:in(TD),16:56:out(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 134)
(59449, '12-Mar-24', 93, '2024-03-12 10:11:33', 'TD', '2024-03-12 18:29:40', 'TD', 498, 41, 0, 'FALSE', '', 0, 0, 0, '', '10:11:in(TD),18:29:out(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 42)
(59450, '13-Mar-24', 93, '2024-03-13 10:08:00', 'TD', '2024-03-13 18:30:25', 'TD', 502, 38, 0, 'FALSE', '', 0, 0, 0, '', '10:08:in(TD),10:08:(TD),18:30:out(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 38)
(59451, '14-Mar-24', 93, '2024-03-14 10:10:40', 'TD', '2024-03-14 18:27:20', 'TD', 497, 40, 0, 'FALSE', '', 0, 0, 0, '', '10:10:in(TD),17:52:out(TD),18:27:in(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 43)
(59452, '15-Mar-24', 93, '2024-03-15 10:10:11', 'TD', '2024-03-15 18:28:09', 'TD', 498, 40, 0, 'FALSE', '', 0, 0, 0, '', '10:10:in(TD),10:10:(TD),18:28:out(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 42)
(59453, '16-Mar-24', 93, '2024-03-16 18:25:02', 'TD', '2024-03-16 18:30:00', 'SE', 5, 535, 0, 'FALSE', '', 0, 0, 0, '', '18:25:in(TD),18:30:out(SE),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'TRUE', 'FALSE', '', '', '', '', '', '', '', '', 0, 535)
(59455, '18-Mar-24', 93, '2024-03-18 10:15:20', 'TD', '2024-03-18 18:35:19', 'TD', 500, 45, 0, 'FALSE', '', 0, 0, 0, '', '10:15:in(TD),17:56:out(TD),18:35:in(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 40)
(59457, '20-Mar-24', 93, '2024-03-20 10:11:45', 'TD', '2024-03-20 18:27:00', 'TD', 496, 41, 0, 'FALSE', '', 0, 0, 0, '', '10:11:in(TD),18:27:out(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 44)
(59458, '21-Mar-24', 93, '2024-03-21 10:32:06', 'TD', '2024-03-21 18:28:26', 'TD', 476, 62, 0, 'FALSE', '', 0, 0, 0, '', '10:32:in(TD),18:28:out(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 64)
(59459, '22-Mar-24', 93, '2024-03-22 10:17:36', 'TD', '2024-03-22 18:31:31', 'TD', 494, 47, 0, 'FALSE', '', 0, 0, 0, '', '10:17:in(TD),18:31:out(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 46)
(59463, '26-Mar-24', 93, '2024-03-26 10:09:54', 'TD', '2024-03-26 18:34:29', 'TD', 505, 39, 0, 'FALSE', '', 0, 0, 0, '', '10:09:in(TD),18:34:out(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 35)
(59464, '27-Mar-24', 93, '2024-03-27 10:06:58', 'TD', '2024-03-27 18:26:40', 'TD', 500, 36, 0, 'FALSE', '', 0, 0, 0, '', '10:06:in(TD),18:26:out(TD),', 5, 1, 0, 'Present', 'P', 'Lt', '', '', 'FALSE', '', '', 0, 0, -1, 'FALSE', 'FALSE', '', '', '', '', '', '', '', '', 0, 40)
86